### ISSUE TITLE
Horizontal margin is used for use label indicators

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [mb340/do-it-yourself-bar#1]
[Upstream Issue #8](https://github.com/wsdfhjxc/do-it-yourself-bar/issues/8) is still present in this release

https://github.com/user-attachments/assets/a20a6c09-0ec4-4d26-86ba-0825d74f732c

**Comment by GM-Script-Writer-62850** [comment]
Note it looks like upstream renamed there account and all issues/pull request ceased to exist as a result
this also breaks some links in the readme

**Comment by mb340** [comment]
Seems like github points to another fork when the original account is deleted. Kinda strange.
